version: "3.3"

services:
  app:
    container_name: jet-terabox
    build:
      context: .
      dockerfile: Dockerfile
    command: sh start.sh  # Change 'bash' to 'sh'
    restart: on-failure
    ports:
      - "80:80"
      - "8080:8080"
